# File Chain (see DEVELOPER.md):
# Doc Version: v1.11.0
# Date Modified: 2026-06-13
#
# - Called by: src/topogen/render.py (offline simple --nac flow)
# - Reads from: TopogenNode/TopogenInterface objects, render context (mode/template/device-template)
# - Writes to: canonical nac.yaml under offline NaC output root
# - Calls into: yaml.safe_dump, pathlib.Path
#
# Purpose: Build and write canonical NaC output for one-router IOS-XE MVP.
# Blast Radius: Medium - affects NaC offline artifact generation when --nac is enabled.

from ipaddress import ip_interface
from pathlib import Path

import yaml

from topogen.models import TopogenError, TopogenNode
from topogen.nac_mgmt_sync import (
    default_sync_mode_from_args,
    mgmt_interface_name,
)


TERRAFORM_MAIN_TF = """# Run Terraform from this nac/ directory so yaml_files = [\"nac.yaml\"] resolves
# to nac.yaml beside main.tf. From the lab root, use:
# terraform -chdir=<lab>/nac <command>
#
# NOTE: the module is pointed at the single nac.yaml via yaml_files. Do NOT use
# yaml_directories = [\".\"] here: it recurses this directory (and .terraform/)
# and ingests the Ansible/informational YAML, which breaks the module's
# yaml_merge (top-level sequences are not valid NaC model fragments).

module \"iosxe\" {
  source     = \"netascode/nac-iosxe/iosxe\"
  version    = \"0.1.0\"
  yaml_files = [\"nac.yaml\"]
}

provider \"iosxe\" {
  # The CiscoDevNet/iosxe provider reads IOSXE_URL, IOSXE_USERNAME, and
  # IOSXE_PASSWORD (or its documented IOSXE_* environment variables).
  # Do not put lab URLs, usernames, or passwords in Terraform files.
  #
  # LAB ONLY: insecure disables TLS certificate verification; acceptable only
  # for throwaway lab gear with self-signed certificates. Never use this for
  # production NaC.
  insecure = true
}
"""


TERRAFORM_VERSIONS_TF = """terraform {
  required_version = \">= 1.8.0\"

  required_providers {
    iosxe = {
      source  = \"CiscoDevNet/iosxe\"
      version = \"0.15.0\"
    }
  }
}
"""


TERRAFORM_TFVARS_EXAMPLE = """# This scaffold is intentionally driven by nac.yaml through yaml_files = [\"nac.yaml\"].
# Supply provider connection settings with environment variables on your runner.
#
# Bash:
#   export IOSXE_URL=\"https://<lab-device-url>\"
#   export IOSXE_USERNAME=\"<lab-username>\"
#   export IOSXE_PASSWORD=\"<lab-password>\"
#
# PowerShell:
#   $env:IOSXE_URL = \"https://<lab-device-url>\"
#   $env:IOSXE_USERNAME = \"<lab-username>\"
#   $env:IOSXE_PASSWORD = \"<lab-password>\"
"""


TERRAFORM_GITIGNORE = """.terraform/
*.tfstate*
terraform.tfvars
"""


ANSIBLE_CFG = """[defaults]
inventory = inventory.yaml
# LAB ONLY: disables SSH host key checks for disposable CML labs.
host_key_checking = False
retry_files_enabled = False
"""


VERIFY_REACHABILITY_YAML = """---
- name: Verify IOS-XE reachability with read-only facts
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather minimal IOS-XE facts
      cisco.ios.ios_facts:
        gather_subset:
          - min
"""


INFORMATIONAL_NAC_NOTE = (
    "Informational only. NOT a Terraform input. The netascode/nac-iosxe module "
    "is driven solely by nac.yaml via yaml_files."
)


def _render_nac_workflow_md(*, default_mode: str, mgmt_enabled: bool) -> str:
    sync_cmd = (
        "python sync-nac-mgmt.py --lab-id <LAB_UUID> --nac-root ."
        if mgmt_enabled
        else "python sync-nac-mgmt.py --lab-id <LAB_UUID> --nac-root . --mode dhcp"
    )
    return f"""# NaC workflow (generated by topogen --nac)

This directory is the Terraform workspace for `netascode/nac-iosxe` device configuration.
TopoGen also emitted helper scripts for live lab management address sync.

## Recommended flow (bootstrap + mgmt-bridge)

1. **Generate** (from repo root; already done if you are reading this in `out/<lab>/nac/`):

   ```bash
   topogen <nodes> --mode flat -T iosv --offline-yaml out/<lab>.yaml \\
     --nac --bootstrap --terraform-cml2 --mgmt --mgmt-bridge [--mgmt-ipv6-mode slaac]
   ```

2. **Bring lab up** with CML2 Terraform (sibling `cml2/` directory):

   ```bash
   terraform -chdir=../cml2 init
   export TF_VAR_address=... TF_VAR_username=... TF_VAR_password=...
   terraform -chdir=../cml2 apply
   ```

   Copy the lab UUID from the CML UI or `terraform -chdir=../cml2 output`.

3. **Sync OOB management addresses** into `nac.yaml`, `inventory.yaml`, and `devices.yaml`:

   ```bash
   cd <lab>/nac
   {sync_cmd}
   ```

   Default sync mode at generation time: **{default_mode}** (`--mode auto` reads `nac_metadata.yaml`).
   Report written to `mgmt_sync.json`.

   **CML 2.10 required for IPv6 OOB sync.** pyATS runs on the **controller** (not your
   laptop). This script uses the CML API (`VIRL2_URL`, `VIRL2_USER`, `VIRL2_PASS`) —
   not CML MCP. Pass `--set-pyats-creds` so nodes have CLI credentials for pyATS
   (defaults: `cisco` / `cisco`, matching bootstrap day-0). If pyATS is unavailable,
   sync falls back to CML L3 snooping on the mgmt interface; use `--cml-snoop-only`
   to force snoop-only. Re-run sync after boot if addresses are not ready yet
   (`terraform wait=true` only guarantees BOOTED).

4. **Apply device configuration** with NaC Terraform:

   ```bash
   export IOSXE_URL=https://<first-router> IOSXE_USERNAME=... IOSXE_PASSWORD=...
   terraform init
   terraform plan
   terraform apply
   ```

5. **Verify** (optional Ansible smoke test):

   ```bash
   ansible-playbook verify_reachability.yaml
   ```

## IPv6 SLAAC extras

When generated with `--mgmt-ipv6-mode slaac`, use `router-hosts.csv` (fill `ipv6_mgmt`
after sync) and `ssh-fanout.py` for parallel SSH checks:

```bash
python ssh-fanout.py --uptime
```

## Environment variables

| Variable | Used by |
|----------|---------|
| `VIRL2_URL`, `VIRL2_USER`, `VIRL2_PASS` | `sync-nac-mgmt.py` (CML API + controller pyATS) |
| `IOSXE_USERNAME`, `IOSXE_PASSWORD`, `IOSXE_ENABLE_PASSWORD` | Optional overrides for `--set-pyats-creds` |
| `IOSXE_URL`, `IOSXE_USERNAME`, `IOSXE_PASSWORD` | `terraform apply` in this directory |

Do not commit credentials or `terraform.tfvars` with secrets.
"""


def _render_sync_nac_mgmt_py(default_mode: str) -> str:
    return f'''#!/usr/bin/env python3
"""Sync NaC OOB mgmt hosts from live CML (generated by topogen --nac).

Default mode at generation: {default_mode}. Use --mode auto to read nac_metadata.yaml.
Requires topogen package: pip install -e .  (or uv sync)
"""
from __future__ import annotations

import sys

from topogen.nac_mgmt_sync import build_argparser, resolve_sync_mode, sync_nac_mgmt

DEFAULT_MODE = "{default_mode}"


def main() -> int:
    parser = build_argparser(default_mode=DEFAULT_MODE)
    if "--mode" not in sys.argv and not any(a.startswith("--mode=") for a in sys.argv):
        parser.set_defaults(mode="auto")
    args = parser.parse_args()
    try:
        mode = resolve_sync_mode(args.mode, nac_root=args.nac_root, default_mode=DEFAULT_MODE)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return sync_nac_mgmt(
        mode=mode,
        nac_root=args.nac_root,
        lab_id=args.lab_id,
        mapping_file=args.mapping_file,
        mgmt_slot=args.mgmt_slot,
        device_template=args.device_template,
        fix_dhcp=args.fix_dhcp,
        cml_snoop_only=args.cml_snoop_only,
        set_pyats_creds=args.set_pyats_creds,
        progress_every=args.progress_every,
    )


if __name__ == "__main__":
    raise SystemExit(main())
'''


ROUTER_HOSTS_CSV_HEADER = "label,canonical,hostname,ipv6_mgmt,user,password\n"


def _normalize_ipv4_host(value) -> str:
    raw = "" if value is None else str(value).strip()
    if not raw:
        return ""
    if "/" in raw:
        try:
            return str(ip_interface(raw).ip)
        except ValueError:
            return ""
    return raw


def _get_iface_value(iface, key: str, default):
    if isinstance(iface, dict):
        return iface.get(key, default)
    return getattr(iface, key, default)


def _interface_label(device_template: str, slot: int) -> str:
    if slot >= 1000:
        return f"Tunnel{slot - 1000}"
    if device_template == "csr1000v":
        return f"GigabitEthernet{slot + 1}"
    return f"GigabitEthernet0/{slot}"


def _split_interface_label(label: str) -> tuple[str, str]:
    for prefix in ("GigabitEthernet", "Tunnel"):
        if label.startswith(prefix):
            return prefix, label[len(prefix):]
    return label, ""


def _configuration_interface_collection(iface_type: str) -> str:
    if iface_type == "GigabitEthernet":
        return "ethernets"
    if iface_type == "Tunnel":
        return "tunnels"
    return f"{iface_type.lower()}s"


_OSPF_ROUTING_TEMPLATES = frozenset({"csr-ospf", "iosv", "csr1000v"})


def _is_ospf_routing_template(template: str) -> bool:
    return str(template) in _OSPF_ROUTING_TEMPLATES


def _build_ospf_routing_config(node_obj: TopogenNode) -> dict:
    """Mirror csr-ospf/iosv day-0: OSPF process 1, area 0, passive Loopback0."""
    networks: list[dict] = []
    loopback = getattr(node_obj, "loopback", None)
    if loopback is not None:
        networks.append(
            {
                "ip": str(loopback.ip),
                "wildcard": "0.0.0.0",
                "area": "0",
            }
        )
    for iface in getattr(node_obj, "interfaces", None) or []:
        if str(_get_iface_value(iface, "description", "")) == "OOB Management":
            continue
        address = _get_iface_value(iface, "address", None)
        if not address:
            continue
        if _get_iface_value(iface, "vrf", None):
            continue
        networks.append(
            {
                "ip": str(ip_interface(address).ip),
                "wildcard": "0.0.0.0",
                "area": "0",
            }
        )
    return {
        "ospf_processes": [
            {
                "id": 1,
                "passive_interfaces": [
                    {
                        "interface_type": "Loopback",
                        "interface_id": "0",
                    }
                ],
                "networks": networks,
            }
        ]
    }


def _order_managed_iface_entry(entry: dict) -> dict:
    """Stable NaC YAML key order for terraform-managed interfaces."""
    order = (
        "type",
        "id",
        "name",
        "shutdown",
        "cdp",
        "ipv4",
        "description",
        "vrf_forwarding",
        "tunnel_source",
        "tunnel_mode",
        "tunnel_destination",
        "tunnel_vrf",
        "ip_mtu",
        "tunnel_protection_ipsec_profile",
    )
    ordered: dict = {}
    for key in order:
        if key in entry:
            ordered[key] = entry[key]
    for key, value in entry.items():
        if key not in ordered:
            ordered[key] = value
    return ordered


def _platform_from_device_template(device_template: str) -> str:
    if device_template in {"iosv", "csr1000v"}:
        return "iosxe"
    raise TopogenError(
        "NaC canonical writer supports IOS-XE templates only "
        f"(iosv, csr1000v); received {device_template}"
    )


DMVPN_TUNNEL_DESCRIPTION = "dmvpn tunnel"
DMVPN_NBMA_DESCRIPTION = "dmvpn nbma"
DMVPN_PAIR_DESCRIPTION = "pair link"
DMVPN_IPSEC_PROFILE = "TOPGEN-IPSEC"
DMVPN_IKEV2_PROPOSAL = "TOPGEN-PROP"
DMVPN_IKEV2_POLICY = "TOPGEN-POL"
DMVPN_IKEV2_KEYRING = "TOPGEN-KR"
DMVPN_IKEV2_PROFILE = "TOPGEN-IKEV2"
DMVPN_IPSEC_TRANSFORM_SET = "TOPGEN-TS"


def _is_dmvpn_context(*, mode: str, template: str) -> bool:
    return mode == "dmvpn" or str(template).endswith("-dmvpn")


def _dmvpn_security_uses_ipsec(security: str | None) -> bool:
    return str(security or "none") in {"ikev2-psk", "ikev2-pki", "ikev2-rsa"}


def _dmvpn_nbma_source_interface(device_template: str) -> str:
    if device_template == "csr1000v":
        return "GigabitEthernet1"
    return "GigabitEthernet0/0"


def _dmvpn_overlay_vrf(args) -> str | None:
    if args is None or not getattr(args, "enable_vrf", False):
        return None
    pair_vrf = getattr(args, "pair_vrf", None)
    return str(pair_vrf) if pair_vrf else None


def _dmvpn_frontside_vrf(args) -> str | None:
    if args is None:
        return None
    fvrf = getattr(args, "dmvpn_fvrf", None)
    return str(fvrf) if fvrf else None


def _collect_dmvpn_vrf_names(args) -> set[str]:
    names: set[str] = set()
    fvrf = _dmvpn_frontside_vrf(args)
    if fvrf:
        names.add(fvrf)
    overlay_vrf = _dmvpn_overlay_vrf(args)
    if overlay_vrf:
        names.add(overlay_vrf)
    return names


def _build_dmvpn_crypto_configuration(args) -> dict | None:
    """Project IKEv2-PSK IPsec stack when day-0 DMVPN security requires it."""
    if args is None:
        return None
    security = getattr(args, "dmvpn_security", "none")
    if security != "ikev2-psk":
        return None
    psk = getattr(args, "dmvpn_psk", None)
    if not psk:
        return None
    fvrf = _dmvpn_frontside_vrf(args)
    ipsec_mode = getattr(args, "dmvpn_ipsec_mode", "transport")
    policy = {
        "name": DMVPN_IKEV2_POLICY,
        "proposals": [DMVPN_IKEV2_PROPOSAL],
    }
    if fvrf:
        policy["match_fvrf"] = fvrf
    profile = {
        "name": DMVPN_IKEV2_PROFILE,
        "authentication_local_pre_share": True,
        "authentication_remote_pre_share": True,
        "keyring_local": DMVPN_IKEV2_KEYRING,
        "match_identity_remote_ipv4_addresses": [
            {"address": "0.0.0.0", "mask": "0.0.0.0"},
        ],
    }
    if fvrf:
        profile["match_fvrf"] = fvrf
    return {
        "ikev2": {
            "proposals": [
                {
                    "name": DMVPN_IKEV2_PROPOSAL,
                    "encryption": ["aes_cbc_256"],
                    "integrity": ["sha256"],
                    "group": ["14"],
                }
            ],
            "policies": [policy],
            "keyrings": [
                {
                    "name": DMVPN_IKEV2_KEYRING,
                    "peers": [
                        {
                            "name": "ANY",
                            "ipv4_address": "0.0.0.0",
                            "ipv4_mask": "0.0.0.0",
                            "pre_shared_key_local": str(psk),
                            "pre_shared_key_remote": str(psk),
                        }
                    ],
                }
            ],
            "profiles": [profile],
        },
        "ipsec_transform_sets": [
            {
                "name": DMVPN_IPSEC_TRANSFORM_SET,
                "esp": "esp-256-aes",
                "esp_hmac": "esp-sha256-hmac",
                "mode_tunnel": ipsec_mode == "tunnel",
            }
        ],
        "ipsec_profiles": [
            {
                "name": DMVPN_IPSEC_PROFILE,
                "set_transform_set": [DMVPN_IPSEC_TRANSFORM_SET],
                "set_ikev2_profile": DMVPN_IKEV2_PROFILE,
            }
        ],
    }


def _apply_dmvpn_tunnel_configuration(
    config_iface_entry: dict,
    *,
    device_template: str,
    args,
    overlay_vrf: str | None,
) -> None:
    config_iface_entry["tunnel_source"] = _dmvpn_nbma_source_interface(device_template)
    ipv4 = dict(config_iface_entry.get("ipv4") or {})
    ipv4["redirects"] = False
    config_iface_entry["ipv4"] = ipv4
    fvrf = _dmvpn_frontside_vrf(args)
    if fvrf:
        config_iface_entry["tunnel_vrf"] = fvrf
        config_iface_entry["ip_mtu"] = 1360
    if overlay_vrf:
        config_iface_entry["vrf_forwarding"] = overlay_vrf
    if _dmvpn_security_uses_ipsec(getattr(args, "dmvpn_security", "none")):
        config_iface_entry["tunnel_protection_ipsec_profile"] = DMVPN_IPSEC_PROFILE


def _canonical_name_for_index(index: int) -> str:
    return f"iosv-{index:02d}"


def _as_nodes(node_or_nodes) -> list[TopogenNode]:
    if isinstance(node_or_nodes, list):
        return node_or_nodes
    return [node_or_nodes]


def _select_host(node: TopogenNode, args) -> str:
    """Select connection host from model data, never from Loopback0."""
    node_interfaces = getattr(node, "interfaces", None) or []
    if bool(getattr(args, "enable_mgmt", False)):
        for iface in node_interfaces:
            description = str(_get_iface_value(iface, "description", ""))
            if description == "OOB Management":
                address = _get_iface_value(iface, "address", None)
                if address:
                    return _normalize_ipv4_host(address)
                ipv6_address = _get_iface_value(iface, "ipv6_address", None)
                if ipv6_address and getattr(args, "mgmt_ipv6_mode", None) == "static":
                    from topogen.nac_mgmt_sync import format_nac_device_host

                    host = str(ipv6_address).split("/")[0]
                    return format_nac_device_host(host)
                if bool(getattr(args, "mgmt_bridge", False)):
                    return ""
        return ""

    data_interfaces = sorted(
        node_interfaces,
        key=lambda iface: _get_iface_value(iface, "slot", 0)
        if _get_iface_value(iface, "slot", None) is not None
        else 0,
    )
    for iface in data_interfaces:
        slot = _get_iface_value(iface, "slot", None)
        try:
            slot = int(0 if slot is None else slot)
        except (TypeError, ValueError):
            slot = 0
        if slot == 0:
            return _normalize_ipv4_host(_get_iface_value(iface, "address", None))
    return ""


def _ipv4_mapping(address) -> dict:
    iface = ip_interface(address)
    return {
        "address": str(iface.ip),
        "address_mask": str(iface.netmask),
    }


def build_canonical_nac_model(
    node: TopogenNode | list[TopogenNode],
    *,
    device_template: str,
    template: str,
    mode: str,
    args=None,
) -> dict:
    """Build canonical NaC model rooted at iosxe.devices[*]."""
    platform = _platform_from_device_template(device_template)
    devices = []
    nodes = _as_nodes(node)
    dmvpn_context = _is_dmvpn_context(mode=mode, template=template)
    dmvpn_overlay_vrf = _dmvpn_overlay_vrf(args) if dmvpn_context else None
    dmvpn_frontside_vrf = _dmvpn_frontside_vrf(args) if dmvpn_context else None
    for index, node_obj in enumerate(nodes, start=1):
        canonical_name = _canonical_name_for_index(index)
        system_hostname = str(getattr(node_obj, "hostname", ""))
        interfaces = []
        config_interface_groups = {}
        vrf_names = set()
        if dmvpn_context:
            vrf_names.update(_collect_dmvpn_vrf_names(args))
        node_interfaces = getattr(node_obj, "interfaces", None) or []
        sorted_interfaces = sorted(
            node_interfaces,
            key=lambda x: _get_iface_value(x, "slot", 0)
            if _get_iface_value(x, "slot", None) is not None
            else 0,
        )
        for iface in sorted_interfaces:
            slot = _get_iface_value(iface, "slot", 0)
            try:
                slot = int(0 if slot is None else slot)
            except (TypeError, ValueError):
                slot = 0
            iface_label = _interface_label(device_template, slot)
            entry = {
                "name": iface_label,
                "slot": slot,
            }
            iface_type, iface_id = _split_interface_label(iface_label)
            config_iface_entry = {"id": str(iface_id)}
            if iface_type == "Tunnel":
                config_iface_entry["name"] = str(iface_id)
            if iface_type == "GigabitEthernet":
                config_iface_entry = {"type": iface_type, **config_iface_entry}
            iface_address = _get_iface_value(iface, "address", None)
            if iface_address:
                entry["ipv4"] = str(iface_address)
                config_iface_entry["ipv4"] = _ipv4_mapping(iface_address)
            iface_description = _get_iface_value(iface, "description", "")
            is_dmvpn_tunnel = (
                dmvpn_context and str(iface_description) == DMVPN_TUNNEL_DESCRIPTION
            )
            is_dmvpn_nbma = (
                dmvpn_context and str(iface_description) == DMVPN_NBMA_DESCRIPTION
            )
            is_dmvpn_pair = (
                dmvpn_context and str(iface_description) == DMVPN_PAIR_DESCRIPTION
            )
            # OOB management is provisioned out-of-band by the CML day-0 template
            # (IPv4: ip address dhcp; IPv6-only: no ip address + ipv6 address …) and is
            # the transport the NaC provider connects through. It must never be emitted as a
            # Terraform-managed interface: writing a fabricated static address on
            # it overlaps data subnets and severs the management session (TG-163).
            # It is retained in the informational fat model and still feeds
            # connection-host selection via _select_host.
            is_oob_mgmt = str(iface_description) == "OOB Management"
            if iface_description:
                entry["description"] = str(iface_description)
                config_iface_entry["description"] = str(iface_description)
            iface_vrf = _get_iface_value(iface, "vrf", None)
            if iface_vrf:
                entry["vrf"] = str(iface_vrf)
                config_iface_entry["vrf_forwarding"] = str(iface_vrf)
                if not is_oob_mgmt:
                    vrf_names.add(str(iface_vrf))
            elif is_dmvpn_nbma and dmvpn_frontside_vrf:
                config_iface_entry["vrf_forwarding"] = dmvpn_frontside_vrf
            elif (is_dmvpn_tunnel or is_dmvpn_pair) and dmvpn_overlay_vrf:
                config_iface_entry["vrf_forwarding"] = dmvpn_overlay_vrf
            interfaces.append(entry)
            if iface_address and not is_oob_mgmt:
                # NaC/terraform-iosxe sets L3 addresses but leaves interfaces
                # administratively down unless shutdown is explicitly false.
                config_iface_entry["shutdown"] = False
                config_iface_entry["cdp"] = True
                if is_dmvpn_tunnel:
                    _apply_dmvpn_tunnel_configuration(
                        config_iface_entry,
                        device_template=device_template,
                        args=args,
                        overlay_vrf=dmvpn_overlay_vrf,
                    )
                collection = _configuration_interface_collection(iface_type)
                config_interface_groups.setdefault(collection, []).append(
                    _order_managed_iface_entry(config_iface_entry)
                )
        loopback = getattr(node_obj, "loopback", None)
        host = _select_host(node_obj, args)
        mgmt_block: dict[str, str] = {"ipv4": host}
        if getattr(args, "mgmt_ipv6_mode", None) == "static":
            for iface in node_interfaces:
                if str(_get_iface_value(iface, "description", "")) == "OOB Management":
                    ipv6_addr = _get_iface_value(iface, "ipv6_address", None)
                    if ipv6_addr:
                        mgmt_block["ipv6"] = str(ipv6_addr)
                    ipv6_ll = _get_iface_value(iface, "ipv6_link_local_address", None)
                    if ipv6_ll:
                        mgmt_block["ipv6_link_local"] = str(ipv6_ll)
                    break
        loopbacks = []
        config_loopbacks = []
        if loopback is not None:
            loopbacks.append(
                {
                    "name": "Loopback0",
                    "ipv4": str(loopback),
                }
            )
            config_loopbacks.append(
                {
                    "id": "0",
                    "ipv4": _ipv4_mapping(loopback),
                }
            )
            if dmvpn_overlay_vrf:
                config_loopbacks[-1]["vrf_forwarding"] = dmvpn_overlay_vrf
        configuration = {
            "system": {
                "hostname": system_hostname,
            },
            "cdp": {
                "run": True,
            },
        }
        if _is_ospf_routing_template(template):
            configuration["routing"] = _build_ospf_routing_config(node_obj)
        if dmvpn_context:
            crypto_config = _build_dmvpn_crypto_configuration(args)
            if crypto_config:
                configuration["crypto"] = crypto_config
        if vrf_names:
            configuration["vrfs"] = [{"name": name} for name in sorted(vrf_names)]
        config_interfaces = {}
        for collection in sorted(config_interface_groups):
            config_interfaces[collection] = config_interface_groups[collection]
        if config_loopbacks:
            config_interfaces["loopbacks"] = config_loopbacks
        if config_interfaces:
            configuration["interfaces"] = config_interfaces
        devices.append(
            {
                "name": canonical_name,
                "host": host,
                "configuration": configuration,
                "hostname": system_hostname,
                "platform": platform,
                "role": "router",
                "template": template,
                "device_template": device_template,
                "mgmt": mgmt_block,
                "loopbacks": loopbacks,
                "interfaces": interfaces,
                "metadata": {
                    "topogen": {
                        "mode": mode,
                        "node_id": system_hostname,
                        "name_source": "synthetic inventory name",
                        "hostname_source": "TopogenNode.hostname",
                    }
                },
            }
        )
    devices = sorted(devices, key=lambda d: d.get("name", ""))
    return {
        "iosxe": {
            "devices": devices
        }
    }


def _has_real_value(value) -> bool:
    if value is None:
        return False
    if value == "":
        return False
    if isinstance(value, (list, tuple, set)):
        return any(_has_real_value(item) for item in value)
    if isinstance(value, dict):
        return any(_has_real_value(item) for item in value.values())
    return True


def _prune_empty_values(value):
    if isinstance(value, list):
        pruned = [_prune_empty_values(item) for item in value]
        return [item for item in pruned if _has_real_value(item)]
    if isinstance(value, dict):
        pruned = {}
        for key, item in value.items():
            next_value = _prune_empty_values(item)
            if _has_real_value(next_value):
                pruned[key] = next_value
        return pruned
    return value


def project_nac_yaml(model: dict) -> dict:
    """Project the fat canonical model into the confirmed lean nac.yaml schema."""
    devices = []
    for device in model.get("iosxe", {}).get("devices", []):
        projected_device = {}
        name = device.get("name")
        if _has_real_value(name):
            projected_device["name"] = name
        host = device.get("host")
        if _has_real_value(host):
            projected_device["host"] = host
        configuration = _prune_empty_values(device.get("configuration", {}))
        if _has_real_value(configuration):
            projected_device["configuration"] = configuration
        if _has_real_value(projected_device):
            devices.append(projected_device)
    return {
        "iosxe": {
            "devices": devices
        }
    }


def write_nac_yaml(model: dict, output_path: Path, overwrite: bool = False) -> Path:
    """Write canonical nac.yaml with deterministic key order."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not overwrite:
        raise TopogenError(
            f"Refusing to overwrite existing file: {output_path}. Use --overwrite to replace it."
        )
    with output_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(
            project_nac_yaml(model),
            handle,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=False,
        )
    return output_path


def _write_static_text(output_path: Path, content: str, overwrite: bool = False) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not overwrite:
        raise TopogenError(
            f"Refusing to overwrite existing file: {output_path}. Use --overwrite to replace it."
        )
    output_path.write_text(content, encoding="utf-8")
    return output_path


def write_terraform_main_tf(output_path: Path, overwrite: bool = False) -> Path:
    """Write the static netascode/nac-iosxe module scaffold."""
    return _write_static_text(output_path, TERRAFORM_MAIN_TF, overwrite=overwrite)


def write_terraform_versions_tf(output_path: Path, overwrite: bool = False) -> Path:
    """Write the Terraform/provider version pins required by nac-iosxe 0.1.0."""
    return _write_static_text(output_path, TERRAFORM_VERSIONS_TF, overwrite=overwrite)


def write_terraform_tfvars_example(output_path: Path, overwrite: bool = False) -> Path:
    """Write placeholder-only provider environment variable guidance."""
    return _write_static_text(output_path, TERRAFORM_TFVARS_EXAMPLE, overwrite=overwrite)


def write_terraform_gitignore(output_path: Path, overwrite: bool = False) -> Path:
    """Write Terraform local-state ignore rules for the nac workspace."""
    return _write_static_text(output_path, TERRAFORM_GITIGNORE, overwrite=overwrite)


def write_terraform_scaffold(nac_root: Path, overwrite: bool = False) -> list[Path]:
    """Write the static Terraform scaffold files under nac_root."""
    return [
        write_terraform_main_tf(nac_root / "main.tf", overwrite=overwrite),
        write_terraform_versions_tf(nac_root / "versions.tf", overwrite=overwrite),
        write_terraform_tfvars_example(nac_root / "terraform.tfvars.example", overwrite=overwrite),
        write_terraform_gitignore(nac_root / ".gitignore", overwrite=overwrite),
    ]


def write_ansible_cfg(output_path: Path, overwrite: bool = False) -> Path:
    """Write the parse-only Ansible config stub."""
    return _write_static_text(output_path, ANSIBLE_CFG, overwrite=overwrite)


def write_verify_reachability_yaml(output_path: Path, overwrite: bool = False) -> Path:
    """Write the read-only Ansible ios_facts smoke playbook."""
    return _write_static_text(output_path, VERIFY_REACHABILITY_YAML, overwrite=overwrite)


def write_inventory_yaml(model: dict, output_path: Path, overwrite: bool = False) -> Path:
    """Project canonical model into deterministic Ansible inventory.yaml."""
    devices = model.get("iosxe", {}).get("devices", [])
    hosts = {}
    for device in sorted(devices, key=lambda d: d.get("name", "")):
        ansible_host = _normalize_ipv4_host(device.get("host") or device.get("mgmt", {}).get("ipv4", ""))
        hosts[device.get("name", "")] = {
            "ansible_host": ansible_host,
            "platform": device.get("platform", ""),
        }
    payload = {"all": {"hosts": hosts}}
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not overwrite:
        raise TopogenError(
            f"Refusing to overwrite existing file: {output_path}. Use --overwrite to replace it."
        )
    with output_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(
            payload,
            handle,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=False,
        )
    return output_path


def write_group_vars_all_yaml(model: dict, output_path: Path, overwrite: bool = False) -> Path:
    """Project canonical model into deterministic group_vars/all.yaml."""
    devices = sorted(model.get("iosxe", {}).get("devices", []), key=lambda d: d.get("name", ""))
    platform = devices[0].get("platform", "") if devices else ""
    payload = {
        "nac_platform": platform,
        "nac_device_count": len(devices),
        "ansible_connection": "ansible.netcommon.network_cli",
        "ansible_network_os": "cisco.ios.ios",
        "ansible_user": "{{ lookup('env', 'IOSXE_USERNAME') }}",
        "ansible_password": "{{ lookup('env', 'IOSXE_PASSWORD') }}",
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not overwrite:
        raise TopogenError(
            f"Refusing to overwrite existing file: {output_path}. Use --overwrite to replace it."
        )
    with output_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(
            payload,
            handle,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=False,
        )
    return output_path


def write_host_vars_yaml(model: dict, host_vars_root: Path, overwrite: bool = False) -> list[Path]:
    """Project canonical model into deterministic host_vars/<device>.yaml files."""
    host_vars_root.mkdir(parents=True, exist_ok=True)
    devices = sorted(model.get("iosxe", {}).get("devices", []), key=lambda d: d.get("name", ""))
    written_paths: list[Path] = []
    for device in devices:
        out_path = host_vars_root / f"{device.get('name', '')}.yaml"
        if out_path.exists() and not overwrite:
            raise TopogenError(
                f"Refusing to overwrite existing file: {out_path}. Use --overwrite to replace it."
            )
        payload = {
            "hostname": device.get("hostname", ""),
            "role": device.get("role", ""),
            "template": device.get("template", ""),
            "device_template": device.get("device_template", ""),
            "loopbacks": device.get("loopbacks", []),
            "interfaces": device.get("interfaces", []),
        }
        with out_path.open("w", encoding="utf-8") as handle:
            yaml.safe_dump(
                payload,
                handle,
                sort_keys=False,
                default_flow_style=False,
                allow_unicode=False,
            )
        written_paths.append(out_path)
    return written_paths


def write_devices_yaml(model: dict, output_path: Path, overwrite: bool = False) -> Path:
    """Project canonical model into deterministic devices.yaml."""
    devices = sorted(model.get("iosxe", {}).get("devices", []), key=lambda d: d.get("name", ""))
    projected_devices = []
    for device in devices:
        mgmt_ip = _normalize_ipv4_host(device.get("host") or device.get("mgmt", {}).get("ipv4", ""))
        projected_devices.append(
            {
                "name": device.get("name", ""),
                "hostname": device.get("hostname", ""),
                "platform": device.get("platform", ""),
                "role": device.get("role", ""),
                "mgmt_ip": mgmt_ip,
            }
        )
    payload = {
        "terraform_input": False,
        "note": INFORMATIONAL_NAC_NOTE,
        "devices": projected_devices,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not overwrite:
        raise TopogenError(
            f"Refusing to overwrite existing file: {output_path}. Use --overwrite to replace it."
        )
    with output_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(
            payload,
            handle,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=False,
        )
    return output_path


def _mgmt_metadata_fields(args, device_template: str) -> dict:
    if not args or not getattr(args, "enable_mgmt", False):
        return {}
    mgmt_slot = int(getattr(args, "mgmt_slot", 5))
    ipv6_mode = getattr(args, "mgmt_ipv6_mode", None)
    ipv4_dhcp = bool(getattr(args, "mgmt_ipv4_dhcp", False))
    mgmt_mode = default_sync_mode_from_args(args)
    fields = {
        "mgmt_mode": mgmt_mode,
        "mgmt_vrf": getattr(args, "mgmt_vrf", None) or "",
        "mgmt_interface": mgmt_interface_name(device_template, mgmt_slot),
        "mgmt_ipv6_mode": ipv6_mode or "",
    }
    if ipv4_dhcp:
        fields["mgmt_ipv4_dhcp"] = True
    if ipv6_mode:
        fields["mgmt_ipv6_only"] = not ipv4_dhcp
    return fields


def write_nac_mgmt_sync_scaffold(
    *,
    nac_root: Path,
    model: dict,
    device_template: str,
    args=None,
    overwrite: bool = False,
) -> list[Path]:
    """Emit sync-nac-mgmt.py, NAC-WORKFLOW.md, and optional IPv6 helper files."""
    default_mode = default_sync_mode_from_args(args)
    mgmt_enabled = bool(args and getattr(args, "enable_mgmt", False))
    written: list[Path] = [
        _write_static_text(
            nac_root / "sync-nac-mgmt.py",
            _render_sync_nac_mgmt_py(default_mode),
            overwrite=overwrite,
        ),
        _write_static_text(
            nac_root / "NAC-WORKFLOW.md",
            _render_nac_workflow_md(default_mode=default_mode, mgmt_enabled=mgmt_enabled),
            overwrite=overwrite,
        ),
    ]

    if getattr(args, "mgmt_ipv6_mode", None) == "slaac":
        ssh_fanout_src = Path(__file__).resolve().parents[2] / "scripts" / "ssh-fanout.py"
        if ssh_fanout_src.is_file():
            written.append(
                _write_static_text(
                    nac_root / "ssh-fanout.py",
                    ssh_fanout_src.read_text(encoding="utf-8"),
                    overwrite=overwrite,
                )
            )
        devices = sorted(model.get("iosxe", {}).get("devices", []), key=lambda d: d.get("name", ""))
        rows = [ROUTER_HOSTS_CSV_HEADER]
        for device in devices:
            hostname = device.get("hostname", device.get("name", ""))
            label = hostname or device.get("name", "")
            rows.append(f"{label},{device.get('name', '')},{hostname},,,\n")
        written.append(
            _write_static_text(
                nac_root / "router-hosts.csv",
                "".join(rows),
                overwrite=overwrite,
            )
        )
    return written


def write_nac_metadata_yaml(
    model: dict,
    output_path: Path,
    overwrite: bool = False,
    *,
    args=None,
    device_template: str = "iosv",
) -> Path:
    """Write deterministic nac_metadata.yaml for canonical outputs."""
    devices = sorted(model.get("iosxe", {}).get("devices", []), key=lambda d: d.get("name", ""))
    first_device = devices[0] if devices else {}
    topogen_metadata = first_device.get("metadata", {}).get("topogen", {})
    host_vars_artifacts = [f"host_vars/{d.get('name', '')}.yaml" for d in devices]
    mgmt_fields = _mgmt_metadata_fields(args, device_template)
    scaffold_artifacts = [
        "sync-nac-mgmt.py",
        "NAC-WORKFLOW.md",
    ]
    if getattr(args, "mgmt_ipv6_mode", None) == "slaac":
        scaffold_artifacts.extend(["ssh-fanout.py", "router-hosts.csv"])
    generated_artifacts = [
        "nac.yaml",
        "main.tf",
        "versions.tf",
        "terraform.tfvars.example",
        ".gitignore",
        "inventory.yaml",
        "ansible.cfg",
        "group_vars/all.yaml",
        *host_vars_artifacts,
        "verify_reachability.yaml",
        "devices.yaml",
        *scaffold_artifacts,
        "nac_metadata.yaml",
    ]
    payload = {
        "terraform_input": False,
        "note": INFORMATIONAL_NAC_NOTE,
        "schema": "iosxe-devices-configuration-mvp",
        "schema_version": "3.0.0",
        "canonical_root": "iosxe.devices[]",
        "contract": "lean iosxe.devices[].configuration.*",
        "epic_ref": "TG-131",
        "module": "netascode/nac-iosxe/iosxe 0.1.0",
        "provider": "CiscoDevNet/iosxe 0.15.0",
        "generator": "topogen",
        "mode": topogen_metadata.get("mode", ""),
        "template": first_device.get("template", ""),
        "device_template": first_device.get("device_template", ""),
        "device_count": len(devices),
        "generated_artifacts": generated_artifacts,
        **mgmt_fields,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and not overwrite:
        raise TopogenError(
            f"Refusing to overwrite existing file: {output_path}. Use --overwrite to replace it."
        )
    with output_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(
            payload,
            handle,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=False,
        )
    return output_path


def write_nac_tree(
    *,
    nac_root: Path,
    device_template: str,
    template: str,
    mode: str,
    node: TopogenNode | None = None,
    nodes: list[TopogenNode] | None = None,
    args=None,
    overwrite: bool = False,
) -> Path:
    """Orchestrate canonical NaC output write tree."""
    selected_nodes = nodes if nodes is not None else ([node] if node is not None else [])
    if not selected_nodes:
        raise TopogenError("NaC writer requires at least one router node")
    model = build_canonical_nac_model(
        selected_nodes,
        device_template=device_template,
        template=template,
        mode=mode,
        args=args,
    )
    nac_root.mkdir(parents=True, exist_ok=True)
    nac_yaml_path = write_nac_yaml(model, nac_root / "nac.yaml", overwrite=overwrite)
    write_terraform_scaffold(nac_root, overwrite=overwrite)
    write_ansible_cfg(
        nac_root / "ansible.cfg",
        overwrite=overwrite,
    )
    write_inventory_yaml(
        model,
        nac_root / "inventory.yaml",
        overwrite=overwrite,
    )
    write_group_vars_all_yaml(
        model,
        nac_root / "group_vars" / "all.yaml",
        overwrite=overwrite,
    )
    write_host_vars_yaml(
        model,
        nac_root / "host_vars",
        overwrite=overwrite,
    )
    write_verify_reachability_yaml(
        nac_root / "verify_reachability.yaml",
        overwrite=overwrite,
    )
    write_devices_yaml(
        model,
        nac_root / "devices.yaml",
        overwrite=overwrite,
    )
    write_nac_mgmt_sync_scaffold(
        nac_root=nac_root,
        model=model,
        device_template=device_template,
        args=args,
        overwrite=overwrite,
    )
    write_nac_metadata_yaml(
        model,
        nac_root / "nac_metadata.yaml",
        overwrite=overwrite,
        args=args,
        device_template=device_template,
    )
    return nac_yaml_path
